### ISSUE TITLE
404s on pages linked via readme

### ISSUE THREAD

**Issue by DawMatt** [dxc-technology/Sequences-as-Code#22]
**Describe the issue**
The github links from the [readme page](https://github.com/dxc-technology/Sequences-as-Code/blob/master/README.md) result in 404s once you go a few levels deep.

**To Reproduce**
1. Go to https://dxc-technology.github.io/Sequences-as-Code/#/
2. Click on 'Your Mission'
3. Click on 'This mission will self destruct in 5 seconds'
4. Click on any link on the diagram

**Actual behaviour**
Every link takes you to a 404 page.

**Expected behavior**
Links take you to the intended page.

**Comment by tom-halpin** [comment]
@DawMatt Thank you for your interest in the application.

I think I have fixed the issue you reported. I would appreciate if you would take a look and close the issue if it is resolved.

**Comment by DawMatt** [comment]
@tom-halpin , that seems to have fixed the issue. Thanks.

**Comment by tom-halpin** [comment]
@DawMatt thanks again for reporting the issue and thus helping us to improve the repository
